<a href="https://colab.research.google.com/github/rafaelfilipedealmeida/data-portfolio/blob/main/titanic_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Dataset Analysis
## Questions I'm answering:
1. What was the survival rate by gender?
2. What was the survival rate by passenger class?
3. What was the average age of survivors vs non-survivors?

1. What was the survival rate by gender?

In [32]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

**Observation:** 74% of women survived compared to only 19% of men.
Gender was the strongest predictor of survival.

2. What was the survival rate by passenger class?

In [33]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

**Observation:** First class passengers had a 63% survival rate compared to 24% in third class.
Socioeconomic status was also a major factor in survival.

3. What was the average age of survivors vs non-survivors?

In [34]:
df.groupby("Survived")["Age"].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

**Observation:** Survivors had an average age of 28 years vs 30 years for non-survivors.
Age had minimal impact compared to gender and class.